### ISSUE TITLE
Webserver doesn't starts

### ISSUE THREAD

**Issue by pbandyop** [cdaller/security_taint_propagation#1]
Hello,
I tried to install your project using the below commands. However, the web server doesn't starts. Please help me. Below are the commands that I ran:

```
git clone https://github.com/cdaller/security_taint_propagation.git
cd security_taint_propagation/
mvn install
cd security_taint_webapp/
mvn jetty:run-forked
```

Both the mvn commands has successfull builds but when I direct my webs browser to `http://localhost:8080/taintwebapp` it says `site cannot be reached`. Please tell me what I am doing wrong.

Thanks!

**Comment by cdaller** [comment]
there seems to be a problem with the forked version of jetty.
mvn jetty:run is starting the application, but without taint propagation :-(

I will check later today to find the problem...

**Comment by cdaller** [comment]
It seems that the order of the jvmargs is important. I fixed it and it should work now.

Looking forward to your feedback!
