### ISSUE TITLE
java.lang.Object can't implements  interface?

### ISSUE THREAD

**Issue by tcsecchen** [cdaller/security_taint_propagation#2]
hello
i want to add interface to java.lang.Object , but i failed, how can i do this

the code:
![default](https://user-images.githubusercontent.com/25191604/46783235-118def80-cd5c-11e8-9dd4-ef79344e90f2.png)

the error:
![default](https://user-images.githubusercontent.com/25191604/46783309-56b22180-cd5c-11e8-81b1-0c7c2ae4f19e.png)

thanks

**Comment by cdaller** [comment]
which java version are you using?
which command did you execute to get this error?

I am using java8 here and a "mvn clean package" works!

**Comment by tcsecchen** [comment]
i use java8 and "mvn clean package" too
i add  "declare parents: java.lang.Object implements TaintedObject;" in the TaintedObjectAspect.aj

**Comment by cdaller** [comment]
it seems that java does not let you change java.lang.Object.
I found that java is quite picky what you can do with those basic Object (in my case java.lang.String) - so not everything is possible/allowed. It seems that java.lang.Object must not be extended like this.

**Comment by tcsecchen** [comment]
uh,thank you very much!

**Comment by cdaller** [comment]
you are welcome - happy that my project is used!
