### ISSUE TITLE
how can setTainted for http body?like getInputStream

### ISSUE THREAD

**Issue by tcsecchen** [cdaller/security_taint_propagation#3]
i want to add interface to java.lang.Object to adapt to all situations,but failed

the http request like this:
![default](https://user-images.githubusercontent.com/25191604/46786673-253f5300-cd68-11e8-8a53-b6e5a1c9727b.png)

it uses json,it will be parsed as a object in java,how can i setTainted for this

Also,now.the project uses getParameter can setTainted for form parameters(Content-Type:application/x-www-form-urlencoded) and url parameters, if the parameters in the http body and use getInputStream or gerReader to get,how can i setTainted for this situation

This is troubling me.
I would be very grateful if you could help me.

**Comment by cdaller** [comment]
I like the idea to set the tainted flag to objects coming from a tainted source. Not sure if you can add the tainted flag to a Stream and inherit that flag to all objects derived from that stream.

I am sorry for not being able to provide a solution for this problem and I do not have time at the moment to give it a try. But you are highly welcome to provide a pull request if you have a solution!

**Comment by tcsecchen** [comment]
ok,i will have a try.
thanks for you help
